name: travel_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  hexcolor: ^3.0.1
  google_fonts: ^4.0.3
  intl_phone_field: ^3.1.0
  google_maps_flutter: ^2.2.5
  location: ^4.1.1
  flutter_google_places: ^0.3.0
  flutter_polyline_points: ^1.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/image/Splash.png
    - assets/image/page1.png
    - assets/image/page2.png
    - assets/image/page3.png
    - assets/image/page4.jpg
    - assets/image/term.png
    - assets/image/term_text.png
    - assets/image/location.png
    - assets/image/meili.png
    - assets/image/arrow_location.png
    
